### PR TITLE
fix: force update revision name

### LINKED ISSUE #12: Named revision won't deploy
### TL;DR
Naming a revision using YAML metadata, will not deploy with correct revision name.

**Expected behavior**
Deployed with revision name (either replace or update).

**Observed behavior**
Deployed to a generated revision name with error `Revision 'NAME' does not exist or is deleted`.

### Reproduction

**Action YAML**

```yaml
 - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        metadata: service.yaml
```

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: NAME
  annotations:
        run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      name: NAME-002
    spec:
      containers:
      - image: gcr.io/...
  traffic:
    - percent: 0
      revisionName: NAME-002
      tag: candidate
    - percent: 100
      revisionName: NAME-001
```

**Repository**

**Additional information**

### PR DESCRIPTION
**Pull request by averikitsch**
Fixes #12 #23

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -145,15 +145,35 @@ export class Service {
...
+        num = '1';
+      }
+      const newSuffix = `-${num.padStart(4, '0')}-${Math.random()
+        .toString(36)
+        .replace(/[^a-z]+/g, '')
+        .substring(0, 3)}`;
+      name = revisionName + newSuffix;
+    }
+
+    if (name.length > 63) name = name.substring(0, 63);
```
Comment (bharathkkb) [inline src/service.ts:171]: IIUC we append a suffix to the name? Can we add some comments to this logic with string manipulations?

Comment (averikitsch) [reply src/service.ts]: Moved this logic to a separate method with better comments. When there is no perceived change in the service a new revision isn't being made. We can force the update with a suffix name change. This mimics the gcloud logic.

**Review by bharathkkb — APPROVED** [review]
